packages:
  - .

allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  '@vercel/speed-insights': false
  esbuild: false

builtDependencies:
  - '@vercel/speed-insights'

onlyBuiltDependencies:
  - '@vercel/speed-insights'
  - esbuild
